server:
  port: 9005

spring:
  application:
    name: kitchen-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${KITCHEN_DB_URL:jdbc:mysql://localhost:3306/kitchen_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${KITCHEN_DB_USERNAME:root}
    password: ${KITCHEN_DB_PASSWORD:}

  sql:
    init:
      mode: always
      continue-on-error: true

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
